# ─────────────────────────────────────────────
# Knox Wedding – Site Configuration
# ─────────────────────────────────────────────

couple:
  partner1:
    name: "Gui"
    shortName: "Gui"
  partner2:
    name: "Mirto"
    shortName: "Mirto"

wedding:
  date: "2026-06-06"
  time: "19:00"
  venue:
    name: "Αγία Άννα"
    address: "Eretria, Greece"
    mapUrl: "https://maps.app.goo.gl/cFBkHtM6AmK45byo7"
    coordinates:
      lat: 36.3512
      lng: 25.3767
  hashtag: "#thejourneybeyond"

schedule:

  - time: "05-06-26 @ 12:00"
    title:
      en: "Join the heroes for an entire day at the beach, drinking and eating at the local beach bar "
      pt: "Junte-se aos heróis para um dia inteiro na praia, bebendo e comendo no bar local da praia "
      el: "Ελάτε να συναντήσετε τους ήρωες για μια ολόκληρη μέρα στην παραλία, πίνοντας και τρώγοντας στο τοπικό beach bar "
    # description:
    #   en: "Spend the day at Chiliadou beach, known for its crystal-clear waters and stunning rock formations. Perfect for swimming, snorkeling, and relaxing under the sun."
    #   pt: "Passe o dia na praia de Chiliadou, conhecida por suas águas cristalinas e formações rochosas deslumbrantes. Perfeita para nadar, fazer snorkel e relaxar ao sol."
    #   el: "Περάστε την ημέρα στην παραλία Χιλιάδου, γνωστή για τα κρυστάλλινα νερά και τις εκπληκτικές βραχώδεις μορφές. Ιδανική για κολύμπι, καταδύσεις με αναπνευστήρα και χαλάρωση κάτω από τον ήλιο."
    icon: "music"
    image: "/images/schedule/going_merry.avif"
    location:
      name:
        en: "Ippokampos Beach Bar"
        pt: "Bar de Praia Ippokampos"
        el: "Beach Bar Ιππόκαμπος"
      url: "https://maps.app.goo.gl/rYpaXUxRqPNFNkX87"
    balloon:
      type: "square"
      pos: "top-0 right-0"
      style:
        width: "300px"
        transform: "translateY(0px)"
    panel:
      span: 14

  - time: "04-06-26 @ 19:00"
    title:
      en: ""
      pt: ""
      el: ""
    # description:
    #   en: "Come join the heroes for an intimate welcome dinner with close family at "
    #   pt: "Venha se juntar aos heróis para um jantar de boas-vindas íntimo com a família próxima "
    #   el: "Ελάτε να συναντήσετε τους ήρωες για ένα οικείο δείπνο καλωσορίσματος με την κοντινή οικογένεια στο "
    icon: "utensils"
    image: "/images/schedule/family_dinner_frieren.png"
    visibleTo:
      - family
    location:
      name:
        en: "Mirto's House"
        pt: "Casa da Mirto"
        el: "Σπίτι της Μύρτου"
      url: "https://goo.gl/maps/1Z5n9sXo7j2Zz8cA9"
    balloon:
      opaque: true
      type: "square"
      style:
        top: "190px"
        left: "40px"
        width: "1000px"
        transform: "translateY(0px)"
    panel:
      span: 6

  - time: "06-06-26 @ 19:00"
    title:
      en: "Join the heroes in their wedding ceremony at the beautiful Agia Anna, for a night of celebration and dancing under the stars"
      pt: "Junte-se aos heróis em sua cerimônia de casamento na bela Agia Anna, para uma noite de celebração e dança sob as estrelas"
      el: "Ελάτε να συναντήσετε τους ήρωες στην τελετή του γάμου τους στην όμορφη Αγία Άννα, για μια νύχτα γιορτής και χορού κάτω από τα αστέρια"
    # description:
    #   en: "Spend the day at Chiliadou beach, known for its crystal-clear waters and stunning rock formations. Perfect for swimming, snorkeling, and relaxing under the sun."
    #   pt: "Passe o dia na praia de Chiliadou, conhecida por suas águas cristalinas e formações rochosas deslumbrantes. Perfeita para nadar, fazer snorkel e relaxar ao sol."
    #   el: "Περάστε την ημέρα στην παραλία Χιλιάδου, γνωστή για τα κρυστάλλινα νερά και τις εκπληκτικές βραχώδεις μορφές. Ιδανική για κολύμπι, καταδύσεις με αναπνευστήρα και χαλάρωση κάτω από τον ήλιο."
    icon: "music"
    image: "/images/schedule/himmel_cutie.png"
    location:
      name:
        en: "Agia Anna"
        pt: "Agia Anna"
        el: "Αγία Άννα"
      url: "https://goo.gl/maps/nndURo4VnTG9VFcw7"
    balloon:
      type: "square"
      pos: "top-0 right-0"
      style:
        width: "300px"
        transform: "translateY(0px)"
    panel:
      # tall: true
      style:
        minHeight: "400px"

  - time: "08-06-26 @ 12:00"
    title:
      en: "Join us in an all day at the best beach of Evia:"
      pt: "O dia todo na melhor praia de Evia:"
      el: "Ολη την ημέρα στην καλύτερη παραλία της Εβίας:"
    # description:
    #   en: "Spend the day at Chiliadou beach. Perfect for swimming, snorkeling, and relaxing under the sun."
    #   pt: "Passe o dia na praia de Chiliadou. Perfeita para nadar, fazer snorkel e relaxar ao sol."
    #   el: "Περάστε την ημέρα στην παραλία Χιλιάδου. Ιδανική για κολύμπι, καταδύσεις με αναπνευστήρα και χαλάρωση κάτω από τον ήλιο."
    icon: "music"
    image: "/images/schedule/frieren_balloon_test_empty.png"
    location:
      name:
        en: "Chiliadou Beach"
        pt: "Praia de Chiliadou"
        el: "Παραλία Χιλιάδου"
      url: "https://maps.app.goo.gl/xBQStJ6592AHRztf7"
    balloon:
      type: "none"
      tail: ""
      maxWidth: "max-w-[25%]"
      style:
        top: "40px"
        left: "46px"
        width: "80px"
        transform: "translateY(-8px)"
        border: "none"
        boxShadow: "none"
    panel:
      span: 8

  - time: "07-06-26 @ 12:00"
    title:
      en: "Join us for brunch at ..."
      pt: "Junte-se a nós para brunch no ..."
      el: "Ελάτε να μας συναντήσετε για brunch στο ..."
    # description:
      # en: "Spend the day at Chiliadou beach. Perfect for swimming, snorkeling, and relaxing under the sun."
      # pt: "Passe o dia na praia de Chiliadou. Perfeita para nadar, fazer snorkel e relaxar ao sol."
      # el: "Περάστε την ημέρα στην παραλία Χιλιάδου. Ιδανική για κολύμπι, καταδύσεις με αναπνευστήρα και χαλάρωση κάτω από τον ήλιο."
    icon: "music"
    image: "/images/schedule/manga1.png"
    location:
      name:
        en: "???????"
        pt: "???????"
        el: "???????"
      url: "https://maps.app.goo.gl/xBQStJ6592AHRztf7"
    panel:
      span: 12
    balloon:
      type: "none"
      tail: ""
      maxWidth: "max-w-[25%]"
      style:
        top: "30px"
        left: "380px"
        width: "80px"
        transform: "translateY(-8px)"
        border: "none"
        boxShadow: "none"

rsvp:
  deadline: "2026-04-15"

defaultLocale: "en"
locales:
  - "en"
  - "pt"
  - "el"

touristicInfo:
  - title:
      en: "1. Brown Beach Chalkida"
      pt: "1. Brown Beach Chalkida"
      el: "1. Brown Beach Chalkida"
    url: "https://maps.app.goo.gl/8dcXT4uLUbKF4tDL6"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "2. Kapetanios"
      pt: "2. Kapetanios"
      el: "2. Kapetanios"
    url: "https://maps.app.goo.gl/D6o1Fmnfm83xfGqh9"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "3. Ouzeri Ten Steps in Sand"
      pt: "3. Ouzeri Ten Steps in Sand"
      el: "3. Ouzeri Ten Steps in Sand"
    url: "https://maps.app.goo.gl/8xdJckUTi4rzB3VEA"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "4. Manteskas"
      pt: "4. Manteskas"
      el: "4. Manteskas"
    url: "https://maps.app.goo.gl/iDTw6Tn2UHRAxd42A"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "5. Limnionas Beach"
      pt: "5. Limnionas Beach"
      el: "5. Limnionas Beach"
    url: "https://maps.app.goo.gl/tjdv9qedHDBmrR8H8"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "6. Eubous"
      pt: "6. Eubous"
      el: "6. Eubous"
    url: "https://maps.app.goo.gl/WJENfrxWucEwnecr7"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "7. Ouzo Nicholas"
      pt: "7. Ouzo Nicholas"
      el: "7. Ouzo Nicholas"
    url: "https://maps.app.goo.gl/ys7bcCzMbre2oRDn9"
    content:
      en: ""
      pt: ""
      el: ""
    icon: "landmark"

  - title:
      en: "8. Paralia Petali"
      pt: "8. Paralia Petali"
      el: "8. Paralia Petali"
    url: "https://maps.app.goo.gl/DrrG2oFNcYxyftcz5"
    content:
      en: "Great beach!"
      pt: "Great beach!"
      el: "Great beach!"
    icon: "landmark"

  - title:
      en: "9. Paralia Vithouri"
      pt: "9. Paralia Vithouri"
      el: "9. Paralia Vithouri"
    url: "https://maps.app.goo.gl/9bVqBMkBiEPQcgsG9"
    content:
      en: "Great beach to visit but difficult access. If you have the budget, we could help you book a boat to take you to several beaches by the coast for 1 day."
      pt: "Great beach to visit but difficult access. If you have the budget, we could help you book a boat to take you to several beaches by the coast for 1 day."
      el: "Great beach to visit but difficult access. If you have the budget, we could help you book a boat to take you to several beaches by the coast for 1 day."
    icon: "landmark"

  - title:
      en: "10. Steni Dirfios"
      pt: "10. Steni Dirfios"
      el: "10. Steni Dirfios"
    url: "https://maps.app.goo.gl/3xnhCYiqEn1BZHRQA"
    content:
      en: "On our way back from Chiliadou (the beach on the Aegean side) we will eat lamb chops in this village."
      pt: "On our way back from Chiliadou (the beach on the Aegean side) we will eat lamb chops in this village."
      el: "On our way back from Chiliadou (the beach on the Aegean side) we will eat lamb chops in this village."
    icon: "landmark"

  - title:
      en: "11. Palaiologos"
      pt: "11. Palaiologos"
      el: "11. Palaiologos"
    url: "https://maps.app.goo.gl/Mzk9KQzwQk1fk8nu7"
    content:
      en: "Also a good tavern on this beach. You can try kalamaraki, shrimp saganaki, fresh fish, zucchini balls, etc."
      pt: "Also a good tavern on this beach. You can try kalamaraki, shrimp saganaki, fresh fish, zucchini balls, etc."
      el: "Also a good tavern on this beach. You can try kalamaraki, shrimp saganaki, fresh fish, zucchini balls, etc."
    icon: "landmark"

  - title:
      en: "12. Amoudia"
      pt: "12. Amoudia"
      el: "12. Amoudia"
    url: "https://maps.app.goo.gl/Y1hZzY3gT2ekk96U7"
    content:
      en: "All of the taverns in this street are nice. I like this one for the location of the tables by the beach."
      pt: "All of the taverns in this street are nice. I like this one for the location of the tables by the beach."
      el: "All of the taverns in this street are nice. I like this one for the location of the tables by the beach."
    icon: "landmark"

  - title:
      en: "13. Asteria Plage"
      pt: "13. Asteria Plage"
      el: "13. Asteria Plage"
    url: "https://maps.app.goo.gl/cnBAeMZ799wHCDJ57"
    content:
      en: "Good coffee place for daytime and bar in the evening. Good food as well but the nighttime only."
      pt: "Good coffee place for daytime and bar in the evening. Good food as well but the nighttime only."
      el: "Good coffee place for daytime and bar in the evening. Good food as well but the nighttime only."
    icon: "landmark"

  - title:
      en: "14. Pericles"
      pt: "14. Pericles"
      el: "14. Pericles"
    url: "https://maps.app.goo.gl/RbyNAFHt1QkExqHE8"
    content:
      en: "Excellent tavern for fish, kalamari, shrimp saganaki, and all the goodies."
      pt: "Excellent tavern for fish, kalamari, shrimp saganaki, and all the goodies."
      el: "Excellent tavern for fish, kalamari, shrimp saganaki, and all the goodies."
    icon: "landmark"

  - title:
      en: "15. Ktina Anthedon"
      pt: "15. Ktina Anthedon"
      el: "15. Ktina Anthedon"
    url: "https://maps.app.goo.gl/ULmQTGPdmkFVHsv6A"
    content:
      en: "Amazing place to have some coffee and watch the sunset. Not for food!"
      pt: "Amazing place to have some coffee and watch the sunset. Not for food!"
      el: "Amazing place to have some coffee and watch the sunset. Not for food!"
    icon: "landmark"

  - title:
      en: "16. Alykes Drosia"
      pt: "16. Alykes Drosia"
      el: "16. Alykes Drosia"
    url: "https://maps.app.goo.gl/VG2WHbCzsG1CVMZR7"
    content:
      en: "On Friday, the day before the wedding, we'll be spending the day here, by the beach!"
      pt: "On Friday, the day before the wedding, we'll be spending the day here, by the beach!"
      el: "On Friday, the day before the wedding, we'll be spending the day here, by the beach!"
    icon: "landmark"

  - title:
      en: "17. Agia Anna"
      pt: "17. Agia Anna"
      el: "17. Agia Anna"
    url: "https://maps.app.goo.gl/gjoQtKs27bsTKnMZ7"
    content:
      en: "This is the wedding location for Saturday afternoon."
      pt: "This is the wedding location for Saturday afternoon."
      el: "This is the wedding location for Saturday afternoon."
    icon: "landmark"

  - title:
      en: "18. Skopelos"
      pt: "18. Skopelos"
      el: "18. Skopelos"
    url: "https://maps.app.goo.gl/ZKxSKdAQUw4XxQYBA"
    content:
      en: "If you can rent a car, you should definitely visit this beautiful island. Easily accessible through the port in Evia."
      pt: "If you can rent a car, you should definitely visit this beautiful island. Easily accessible through the port in Evia."
      el: "If you can rent a car, you should definitely visit this beautiful island. Easily accessible through the port in Evia."
    icon: "landmark"

  - title:
      en: "19. Skiathos"
      pt: "19. Skiathos"
      el: "19. Skiathos"
    url: "https://maps.app.goo.gl/EBrDWQdbZSuhS19P7"
    content:
      en: "If you have some time, and budget, visit this easy to access island by boat. No need to rent a car on this island."
      pt: "If you have some time, and budget, visit this easy to access island by boat. No need to rent a car on this island."
      el: "If you have some time, and budget, visit this easy to access island by boat. No need to rent a car on this island."
    icon: "landmark"

  - title:
      en: "20. Paralia Chiliadou"
      pt: "20. Paralia Chiliadou"
      el: "20. Paralia Chiliadou"
    url: "https://maps.app.goo.gl/TmEeaijg4X1ognMD9"
    content:
      en: "Gui and Mirto will go to this beautiful beach on Monday after the wedding! You may join, but it's more than 1 hour driving over the mountain."
      pt: "Gui and Mirto will go to this beautiful beach on Monday after the wedding! You may join, but it's more than 1 hour driving over the mountain."
      el: "Gui and Mirto will go to this beautiful beach on Monday after the wedding! You may join, but it's more than 1 hour driving over the mountain."
    icon: "landmark"

weddingInfo:
  dressCode:
    en: "The ceremony is outdoors in a forest clearing. Wear whatever feels right for you--comfortable shoes are highly recommended (stilettos might not love the terrain)."
    pt: "A localização é ao ar livre em uma pequena área de floresta. Use o que quiser, mas saltos finos provavelmente não são uma boa escolha."
    el: "Η τοποθεσία είναι έξω σε μια μικρή περιοχή δάσους. Φορέστε ό,τι θέλετε, αλλά τα stilettos πιθανόν να μην είναι καλή επιλογή."
  contacts:
    en: "For any questions, reach out to us at example@email.com or +1 234 567 890."
    pt: "Para qualquer dúvida, entre em contato conosco em example@email.com ou +1 234 567 890."
    el: "Για οποιαδήποτε ερώτηση, επικοινωνήστε μαζί μας στο example@email.com ή +1 234 567 890."
  gifts:
    en: |
      Your presence is the best gift—seriously, no pressure to bring anything! If you'd like to contribute, we're set up for:
      
      1. Cash (always handy for the adventure ahead)
      2. Bank transfer (details below)
      - Revolut: [wise.com/pay/me/guilhermes736](https://wise.com/pay/me/guilhermes736)
      - Wise: [revolut.me/playstationwaifu](https://revolut.me/playstationwaifu)

      Thank you for being part of our journey!
    pt: |
      A sua presença é o melhor presente — a sério, sem pressão para trazer nada! Se quiser contribuir, estamos preparados para:
      1. Dinheiro (sempre útil para a aventura que vem)
      2. Transferência bancária (detalhes abaixo)
      - Revolut: [wise.com/pay/me/guilhermes736](https://wise.com/pay/me/guilhermes736)
      - Wise: [revolut.me/playstationwaifu](https://revolut.me/playstationwaifu)

      Obrigado por fazer parte da nossa jornada!
    el: |
      Η παρουσία σας είναι το καλύτερο δώρο — σοβαρά, κανένας δεν χρειάζεται να φέρει τίποτα! Αν θέλετε να συνεισφέρετε, έχουμε διαθέσιμες επιλογές:
      1. Μετρητά (πάντα χρήσιμα για την επόμενη περιπέτεια)
      2. Τραπεζική μεταφορά (λεπτομέρειες παρακάτω)
      - Revolut: [wise.com/pay/me/guilhermes736](https://wise.com/pay/me/guilhermes736)
      - Wise: [revolut.me/playstationwaifu](https://revolut.me/playstationwaifu)

      Ευχαριστούμε που είστε μέρος του ταξιδιού μας!

  accommodation:
    en: "We have booked accommodation close to the venue for the nights of the 5th and 6th, so you don't have to worry about that. More details will follow to each guest once you have RSVP'd."
    pt: "Reservamos quartos/airbnbs perto do local para as noites de 5 e 6. Mais detalhes serão enviados a cada convidado assim que você confirmar presença."
    el: "Κλείσαμε δωμάτια/airbnbs κοντά στον χώρο για τις νύχτες της 5ης και 6ης. Περισσότερες λεπτομέρειες θα ακολουθήσουν σε κάθε καλεσμένο μόλις επιβεβαιώσετε την παρουσία σας."